project:
  type: book

book:
  title: "Sam Kestin describes 50 years in the Yiddish Theater"
  author: "Sam Kestin (Kasten), translated by <a href = 'https://sjspielman.github.io' style='color:#18BC9C;'>Stephanie Spielman</a>"
  translator: "Stephanie Spielman"
  chapters:
    - index.qmd
    - part: "Part 1: Early life in Ukraine"
      chapters:
        - chapters/01_1946-09-07.qmd
        - chapters/02_1946-09-19.qmd
        - chapters/03_1946-09-21.qmd
        - chapters/04_1946-09-25.qmd
        - chapters/05_1946-09-28.qmd
    - part: "Part 2: Making a living in America"
      chapters:
        - chapters/06_1946-10-03.qmd
        - chapters/07_1946-10-10.qmd
        - chapters/08_1946-10-12.qmd
        - chapters/09_1946-10-17.qmd
        - chapters/10_1946-10-19.qmd
        - chapters/11_1946-10-24.qmd
        - chapters/12_1946-10-26.qmd
    - part: "Part 3: Traveling the provinces"
      chapters:
        - chapters/13_1946-10-31.qmd
        - chapters/14_1946-11-02.qmd
        - chapters/15_1946-11-07.qmd
        - chapters/16_1946-11-09.qmd
        - chapters/17_1946-11-14.qmd
        - chapters/18_1946-11-16.qmd
        - chapters/19_1946-11-21.qmd
        - chapters/20_1946-11-23.qmd
        - chapters/21_1946-11-28.qmd
        - chapters/22_1946-11-30.qmd
        - chapters/23_1946-12-05.qmd
        - chapters/24_1946-12-07.qmd
        - chapters/25_1946-12-12.qmd
    - part: "Part 4: A regular actor in New York"
      chapters:
        - chapters/26_1946-12-14.qmd
        - chapters/27_1946-12-19.qmd
        - chapters/28_1946-12-21.qmd
        - chapters/29_1946-12-26.qmd
        - chapters/30_1946-12-28.qmd 
    - part: "Appendices"
      chapters:
        - appendices/people.qmd
        - appendices/timeline.qmd

  page-footer: '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />Except images and newspaper clippings, this work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.'
  google-analytics: "G-WWFS41KSZH"

format:
  html:
    sidebar-width: 600px
    fontsize: 14px;

theme:
  light: flatly
  dark: darkly